name: Setup and Connect RDP with Tailscale

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download and install Tailscale
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup-latest.exe"
        Start-Process -FilePath "tailscale-setup-latest.exe" -ArgumentList "/silent" -Wait
        Write-Host "Tailscale installed successfully."

    - name: Verify Tailscale installation
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" version
        Write-Host "Tailscale version checked."

    - name: Add Tailscale AuthKey
      run: |
        $authKey = "${{ secrets.TAILSCALE_AUTHKEY }}"
        Write-Host "Using Tailscale AuthKey: $authKey"
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=$authKey
        Write-Host "Tailscale auth key added successfully."
        Start-Sleep -Seconds 10

    - name: Enable Remote Desktop
      run: |
        # Mengaktifkan Remote Desktop
        $regKey = "HKLM:\System\CurrentControlSet\Control\Terminal Server"
        Set-ItemProperty -Path $regKey -Name "fDenyTSConnections" -Value 0

        # Dapatkan IP Tailscale yang aktif
        $tailscaleIP = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        Write-Host "Active Tailscale IP: $tailscaleIP"

        # Membuka port RDP (3389) di Windows Firewall untuk IP Tailscale aktif
        New-NetFirewallRule -Name "Allow Tailscale RDP" -DisplayName "Allow RDP for Active Tailscale IP" -Enabled True -Protocol TCP -Action Allow -LocalPort 3389 -RemoteAddress $tailscaleIP
        Write-Host "RDP enabled and port 3389 opened in Windows Firewall for Tailscale IP: $tailscaleIP."

    - name: Get Tailscale IP address
      run: |
        $tailscaleIP = & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        Write-Host "Tailscale IP Address: $tailscaleIP"

    - name: Start RDP session
      run: |
        Write-Host "Access RDP using the Tailscale IP and login with username 'Administrator' and password 'HenCoders2024'"
        Start-Sleep -Seconds 5

    - name: Keep printing status for 6 hours
      run: |
        $endTime = (Get-Date).AddHours(6)
        while ((Get-Date) -lt $endTime) {
          Write-Host "HenRdp Aktif setiap menit"
          Start-Sleep -Seconds 60
        }
